services:
  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
      - /etc/ssl/certs:/etc/ssl/certs:ro

    restart: unless-stopped

  web:
    build: .
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_KEEP_ALIVE=300s
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  ollama_data: