services:
  web:
    build: .
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Critical for Windows
    environment:
      - DEBUG=False
      - OLLAMA_HOST=http://host.docker.internal:11434
      - OLLAMA_KEEP_ALIVE=300s
      - OLLAMA_ORIGINS=*
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --timeout-keep-alive 300